---
title: "lab1"
format: html
editor: visual
---

## Цель работы

Получить сведения о системе

## Исходные данные

1\. Программное обеспечение astralinux

2\. Rstudio

## План

1.  Получить сведения версию ядра
2.  Получить полные сведения о ядре
3.  Используемый дистрибутив
4.  Получить модель процессора
5.  Скрытые файлы

## Шаги:

1.  Получаем версию ядра при помощи команды uname -r

```{bash}
uname -r
```

2.  Получаем полные сведения о ядре при помощи команды uname -a

```{bash}
uname -a
```

3.  Используей дистрибутив получаем при помощи команды lsb_release -a

```{bash}
lsb_release -a
```

4.  Полную информацию получаем при помощи команды cat /proc/cpuinfo

```{bash}
cat /proc/cpuinfo 
```

5.  Модель процессора получаем при помощи команды cat /proc/cpuinfo \| grep "model name"

```{bash}
cat /proc/cpuinfo | grep "model name"
```

6.  Все скрытые файлы смотрим при помощи команды ls -a

```{bash}
ls -a
```

##Оценка результата
В результате лабораторной работы мы получили основную информацию об системе

## Вывод
Таким образом, я научился работать с базовыми командами Linux для получения сведений об операционной системе

